FROM python:3
LABEL maintainer "Nick NK <n47@paragenesis.ru>"
#ENV PORT=5000
#ENV ADDRESS="0.0.0.0"
#ENV DEBUG=0

COPY . /app
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["./run.sh"]
#CMD ["python", "./app.py", "-p", "echo ${PORT}", "-a", "${ADDRESS}", "-d", "${DEBUG}"]